Practica/Controllers/SystemUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Taller_Entregable.Controllers
{
    public class SystemUserController : Controller
    {
        // GET: SystemUser
        public ActionResult Index()
        {
            return View();
        }
    }
}

Practica/Views/SystemUser/Index.cshtml
@model Modelo.Entidades.SystemUser

<div class="jumbotron">
    <h1>Inicio</h1>
</div>
<div class="row">
    <div class="col-md-4">
        <h2>Bienvenido</h2>
    </div>
    @if (Session["LoginUser"] == null)
    {
        <div class="col-md-6">
            @using (Html.BeginForm("index", "SystemUser", null, FormMethod.Post, new { Id = "FormLogin" }))
            {
                @Html.AntiForgeryToken()

                <div class="form-horizontal">
                    <h4>Login</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                    <div class="form-group">
                        @Html.LabelFor(model => model.Usuario, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Usuario, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Usuario, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Clave, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @*@Html.EditorFor(model => model.Clave, new { htmlAttributes = new { @class = "form-control" } })*@
                            @Html.PasswordFor(model => model.Clave, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.Clave, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    @if (Session["Login"] != null)
                    {
                        <span class="text-danger">@Session["Login"].ToString()</span>
                    }
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Log In" class="btn btn-default" />
                        </div>
                    </div>
                </div>
            }
        </div>
    }
    else
    {
        <p>Has ingresado al sistema, bienvenido @Session["LoginUser"].ToString()</p>
    }
</div>
<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>